### ISSUE TITLE
Where is the wixel in the data abstraction?

### ISSUE THREAD

**Issue by ijustlovemath** [StephenBlackWasAlreadyTaken/wixel-xDrip#30]
Is it transmitter -> BLE receiver -> wixel -> usb -> computer?

Or is it transmitter -> wixel -> BLE transmitter -> android -> xDrip?

Is it possible to have the packets be read into a computer instead of an android phone?

**Comment by StephenBlackWasAlreadyTaken** [comment]
it goes transmitter to wixel to ble to xdrip/android

if you want it to go to a computer, just plug the wixel in to a computer running a serial terminal like coolterm or screen or something, the xdrip-wixel code is set up to send the data over usb if it see its plugged in through usb automatically

**Comment by ijustlovemath** [comment]
Great, thanks!
