### ISSUE TITLE
Receiving very large numbers for dex_(ppkt->raw)

### ISSUE THREAD

**Issue by ijustlovemath** [StephenBlackWasAlreadyTaken/wixel-xDrip#34]
Using the wixel as the receiver, I have been getting very weird numbers for my glucose values. My settings:

* RTS/CTS hardware flow control
* \n termination char 
* baud rate of 9600

I added another part to print_packet that shows ppkt->raw. So my output is: 'ppkt->raw dex_num_decoder(ppkt->raw TRANSMITTER_BATTERY WIXELBATTERY'

A couple readings and their associated G4 values:

98: n/a 117888 215 0
89: 36298 141920 215 0
86: 19848 148000 215 0

Am I just not interpreting the values right?

**Comment by StephenBlackWasAlreadyTaken** [comment]
Im not super sure what you are refering too, if you want to paste your print line here I may be able to help more. But anticipate the raw value to bg conversion to be around ((raw/100)*1.05) - 28 or so, these numbers depend on the age of your sensor and the sensor itself, this is why a calibration algorithm is needed

**Comment by ijustlovemath** [comment]
Those were the print lines! Just added a field, and put the actual value to
the left of the colon. Where did you get that fit? Where can I find the
calibration algorithm? Is it in the xDrip source?

**Comment by StephenBlackWasAlreadyTaken** [comment]
xdrip has its own algorithm that can be found in the calibration model, its a weighted least squares linear regression (weights are age of calibration(linear but should be exponential in the future), sensor confidence(parabolic) and slope confidence(linear)), its split up using LaGrange interpolation because Its the only way I could figgure to write it out in java

**Comment by ijustlovemath** [comment]
So raw/1000 is always used, but the coefficients (1.05 and -28) are calculated for the individual using least squares. It's usually a linear fit then? Or did you say exponential was better?

**Comment by ijustlovemath** [comment]
Also, is the 1.05, -28 the inital approx, for low numbers of values?

**Comment by StephenBlackWasAlreadyTaken** [comment]
yeah I always divide by 1000 first to get the numbers more familiar, but you dont have to, you could just have your slope account for that.
I find there is some curvature at the higher end but its fairly linear, and yeah the 1.05 and the -28 are just rough approximations, a slope of around 1 is fairly common and -30ish seems to be the default intercept, though its not always a good fit, its a good way to estimate if you dont have any calibration data yet

**Comment by ijustlovemath** [comment]
I can't believe I thought I would avoid using statistics in this project of mine :) Thanks, you've been helpful as always.
