### ISSUE TITLE
Cant pair with bluetooth

### ISSUE THREAD

**Issue by danpowell88** [StephenBlackWasAlreadyTaken/wixel-xDrip#47]
The device shows up at BT05 on my phone and when I try to pair with it I see "Pairing rejected by BT05".

I'm using code from master as of right now, the only thing that is different to the specs is teh bluetooth module is the CC41 instead of the HM10 however it sounded like the code now supported this?

Any ideas here, do I have to try and flash the CC41 or do something else?

It all appears to be working with LEDs blinking etc on both the wixel and the ble module but I just can't pair with it.

**Comment by StephenBlackWasAlreadyTaken** [comment]
Are you trying to connect with it from within the  xDrip app? Or in phone
settings?

You will want to do it in the xDrip app and make sure you have the proper
collection method set

**Comment by danpowell88** [comment]
All sorted!

**Comment by embhobbb** [comment]
I am also facing same problem. Can you please tell me how to solve this problem.

**Comment by ivivekgarg** [comment]
Hey I am facing the same issue can you please help ?

**Comment by srisowmya2000** [comment]
I am also  facing the same problem

**Comment by kish0308** [comment]
Same Here Also ..
Rejected by BT05

**Comment by Lagodish** [comment]
Same mf
